# Generated by Django 5.1.5 on 2025-01-30 11:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Quote',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('car_registration', models.CharField(max_length=20)),
                ('year_of_make', models.IntegerField()),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('approved', 'Approved'), ('rejected', 'Rejected')], default='pending', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Windscreen',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('plain', 'Plain'), ('sensor-heated', 'With Sensor - Heated'), ('sensor-non-heated', 'With Sensor - Non-Heated'), ('sensor-heated-camera', 'With Sensor - Heated, Camera'), ('sensor-heated-no-camera', 'With Sensor - Heated, No Camera'), ('partially-heated', 'Partially Heated'), ('fully-heated', 'Fully Heated'), ('side-sensor', 'With Side Sensor'), ('middle-sensor', 'With Middle Sensor'), ('one-camera-sensor', 'With One Camera and a Sensor'), ('camera-only', 'Camera Only'), ('one-camera', 'With One Camera'), ('two-camera-sensor', 'With Two Cameras and a Sensor'), ('three-camera-sensor', 'With Three Cameras and a Sensor'), ('three-camera-only', 'Only Three Cameras')], max_length=50)),
                ('category', models.CharField(choices=[('front-glass', 'Front Glass'), ('rear-glass', 'Rear Glass'), ('door-glass', 'Door Glass'), ('side-glass', 'Side Glass'), ('frames', 'Frames'), ('silicon', 'Silicon')], max_length=50)),
                ('make', models.CharField(choices=[('toyota', 'Toyota'), ('nissan', 'Nissan'), ('honda', 'Honda'), ('mazda', 'Mazda'), ('subaru', 'Subaru'), ('mitsubishi', 'Mitsubishi'), ('suzuki', 'Suzuki'), ('isuzu', 'Isuzu'), ('audi', 'Audi'), ('bmw', 'BMW'), ('mercedes-benz', 'Mercedes-Benz'), ('volkswagen', 'Volkswagen'), ('ford', 'Ford'), ('hyundai', 'Hyundai'), ('kia', 'Kia'), ('land-rover', 'Land Rover')], max_length=50)),
                ('model', models.CharField(max_length=50)),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('is_available', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('quote', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='windscreen_app.quote')),
            ],
        ),
        migrations.AddField(
            model_name='quote',
            name='windscreen',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='windscreen_app.windscreen'),
        ),
    ]
