# Generated by Django 5.1.6 on 2025-02-17 14:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('windscreen_app', '0002_category_vehiclemake_windscreencategory_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Service',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('cost', models.DecimalField(decimal_places=2, default=100, max_digits=10)),
            ],
        ),
        migrations.RemoveField(
            model_name='insuranceprovider',
            name='category',
        ),
        migrations.RenameField(
            model_name='windscreen',
            old_name='category',
            new_name='windscreen_category',
        ),
        migrations.RenameField(
            model_name='windscreencategory',
            old_name='name',
            new_name='type',
        ),
        migrations.RemoveField(
            model_name='windscreen',
            name='make',
        ),
        migrations.RemoveField(
            model_name='windscreen',
            name='model',
        ),
        migrations.RemoveField(
            model_name='windscreen',
            name='type',
        ),
        migrations.RemoveField(
            model_name='windscreencategory',
            name='description',
        ),
        migrations.AddField(
            model_name='windscreencategory',
            name='customizations',
            field=models.JSONField(default=2),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='vehicle',
            name='make',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='windscreen_app.vehiclemake'),
        ),
        migrations.AlterField(
            model_name='vehicle',
            name='model',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='windscreen_app.vehiclemodel'),
        ),
        migrations.AddField(
            model_name='windscreen',
            name='service',
            field=models.ForeignKey(default=2, on_delete=django.db.models.deletion.CASCADE, related_name='windscreens', to='windscreen_app.service'),
            preserve_default=False,
        ),
        migrations.CreateModel(
            name='ServiceCost',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cost', models.DecimalField(decimal_places=2, max_digits=10)),
                ('insurance_provider', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='windscreen_app.insuranceprovider')),
                ('service', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='costs', to='windscreen_app.service')),
                ('vehicle_make', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='windscreen_app.vehiclemake')),
                ('vehicle_model', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='windscreen_app.vehiclemodel')),
            ],
        ),
        migrations.DeleteModel(
            name='Category',
        ),
    ]
