# Generated by Django 5.1.6 on 2025-02-18 13:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('windscreen_app', '0003_service_remove_insuranceprovider_category_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='servicecost',
            name='insurance_provider',
        ),
        migrations.RemoveField(
            model_name='servicecost',
            name='service',
        ),
        migrations.RemoveField(
            model_name='servicecost',
            name='vehicle_make',
        ),
        migrations.RemoveField(
            model_name='servicecost',
            name='vehicle_model',
        ),
        migrations.RemoveField(
            model_name='vehicle',
            name='make',
        ),
        migrations.RemoveField(
            model_name='vehiclemodel',
            name='make',
        ),
        migrations.RemoveField(
            model_name='vehicle',
            name='model',
        ),
        migrations.RemoveField(
            model_name='windscreen',
            name='service',
        ),
        migrations.RemoveField(
            model_name='windscreen',
            name='windscreen_category',
        ),
        migrations.AlterField(
            model_name='service',
            name='cost',
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
        migrations.CreateModel(
            name='Quote',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quote_number', models.CharField(max_length=20, unique=True)),
                ('total_cost', models.DecimalField(decimal_places=2, max_digits=10)),
                ('status', models.CharField(choices=[('Pending', 'Pending'), ('Approved', 'Approved')], default='Pending', max_length=20)),
                ('services', models.ManyToManyField(to='windscreen_app.service')),
                ('vehicle', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='windscreen_app.vehicle')),
            ],
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order_number', models.CharField(max_length=20, unique=True)),
                ('status', models.CharField(choices=[('Working Progress', 'Working Progress'), ('Completed', 'Completed')], default='Working Progress', max_length=20)),
                ('quote', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='windscreen_app.quote')),
            ],
        ),
        migrations.DeleteModel(
            name='InsuranceProvider',
        ),
        migrations.DeleteModel(
            name='ServiceCost',
        ),
        migrations.DeleteModel(
            name='VehicleMake',
        ),
        migrations.DeleteModel(
            name='VehicleModel',
        ),
        migrations.DeleteModel(
            name='Windscreen',
        ),
        migrations.DeleteModel(
            name='WindscreenCategory',
        ),
    ]
