# Generated by Django 5.1.6 on 2025-02-20 12:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('windscreen_app', '0005_insuranceprovider_vehiclemake_windscreentype_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserDetails',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=255)),
                ('kra_pin', models.CharField(max_length=20, unique=True)),
                ('phone', models.CharField(max_length=15)),
            ],
        ),
    ]
