# Generated by Django 5.1.6 on 2025-02-25 14:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('windscreen_app', '0009_remove_order_services_remove_order_status_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='quote',
            name='deleted',
        ),
    ]
