# Generated by Django 5.1.6 on 2025-02-25 14:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('windscreen_app', '0011_alter_vehicle_registration_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vehicle',
            name='year_of_make',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
