# Generated by Django 5.1.6 on 2025-02-25 15:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('windscreen_app', '0012_alter_vehicle_year_of_make'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vehicle',
            name='year_of_make',
            field=models.IntegerField(default=2000),
        ),
    ]
