# Generated by Django 5.1.6 on 2025-02-27 08:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('windscreen_app', '0014_alter_vehicle_registration_number_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='SatisfactionNote',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pdf', models.FileField(upload_to='satisfaction_notes/')),
                ('order', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='satisfaction_note', to='windscreen_app.order')),
            ],
        ),
        migrations.CreateModel(
            name='VehicleImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='vehicle_images/')),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='vehicle_images', to='windscreen_app.order')),
            ],
        ),
        migrations.CreateModel(
            name='WindscreenStock',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.PositiveIntegerField(default=0)),
                ('windscreen_type', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='windscreen_app.windscreentype')),
            ],
        ),
        migrations.CreateModel(
            name='WorkingProgress',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_windscreen_available', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('assigned_windscreen', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='windscreen_app.windscreentype')),
                ('order', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='working_progress', to='windscreen_app.order')),
            ],
        ),
    ]
