# Generated by Django 5.1.6 on 2025-02-27 10:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('windscreen_app', '0015_satisfactionnote_vehicleimage_windscreenstock_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='vehicleimage',
            name='order',
        ),
        migrations.RemoveField(
            model_name='windscreenstock',
            name='windscreen_type',
        ),
        migrations.RemoveField(
            model_name='workingprogress',
            name='assigned_windscreen',
        ),
        migrations.RemoveField(
            model_name='workingprogress',
            name='order',
        ),
        migrations.DeleteModel(
            name='SatisfactionNote',
        ),
        migrations.DeleteModel(
            name='VehicleImage',
        ),
        migrations.DeleteModel(
            name='WindscreenStock',
        ),
        migrations.DeleteModel(
            name='WorkingProgress',
        ),
    ]
