# Generated by Django 5.1.6 on 2025-02-27 11:46

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('windscreen_app', '0016_remove_vehicleimage_order_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='WorkProgress',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('vehicle_reg_no', models.CharField(max_length=20)),
                ('description', models.TextField()),
                ('image1', models.ImageField(blank=True, null=True, upload_to='work_progress/')),
                ('image2', models.ImageField(blank=True, null=True, upload_to='work_progress/')),
                ('pdf_file', models.FileField(blank=True, null=True, upload_to='work_progress/', validators=[django.core.validators.FileExtensionValidator(['pdf'])])),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
