# Generated by Django 5.1.6 on 2025-03-01 15:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('windscreen_app', '0017_workprogress'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='services',
            field=models.ManyToManyField(related_name='orders', to='windscreen_app.service'),
        ),
        migrations.AddField(
            model_name='workprogress',
            name='services',
            field=models.ManyToManyField(related_name='work_progress', to='windscreen_app.service'),
        ),
        migrations.CreateModel(
            name='Invoice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('invoice_number', models.CharField(max_length=255, unique=True)),
                ('total_cost', models.DecimalField(decimal_places=2, max_digits=10)),
                ('paid_amount', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('unpaid_amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('invoice_date', models.DateTimeField(auto_now_add=True)),
                ('due_date', models.DateTimeField()),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('paid', 'Paid'), ('overdue', 'Overdue')], default='Pending', max_length=20)),
                ('payment_method', models.CharField(blank=True, choices=[('cash', 'Cash'), ('mpesa', 'Mpesa'), ('mobile_money', 'Mobile Money'), ('bank_transfer', 'Bank Transfer'), ('card', 'Card')], max_length=20, null=True)),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='invoices', to='windscreen_app.userdetails')),
                ('order', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='invoice', to='windscreen_app.order')),
                ('services', models.ManyToManyField(to='windscreen_app.service')),
            ],
        ),
        migrations.CreateModel(
            name='StatementOfAccount',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('statement_period_start', models.DateField()),
                ('statement_period_end', models.DateField()),
                ('opening_balance', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('total_invoiced', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('total_paid', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('closing_balance', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('generated_at', models.DateTimeField(auto_now_add=True)),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='statements', to='windscreen_app.userdetails')),
                ('transactions', models.ManyToManyField(to='windscreen_app.invoice')),
            ],
        ),
    ]
