# Generated by Django 5.1.6 on 2025-03-01 15:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('windscreen_app', '0018_order_services_workprogress_services_invoice_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='workprogress',
            name='order',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='work_progress', to='windscreen_app.order'),
        ),
    ]
