# Generated by Django 5.1.6 on 2025-03-03 08:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('windscreen_app', '0019_workprogress_order'),
    ]

    operations = [
        migrations.AddField(
            model_name='quote',
            name='registration_number',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
