# Generated by Django 5.1.6 on 2025-03-06 10:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('windscreen_app', '0021_alter_workprogress_vehicle_reg_no'),
    ]

    operations = [
        migrations.AddField(
            model_name='quote',
            name='vehicle',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='quotes', to='windscreen_app.vehicle'),
        ),
        migrations.AddField(
            model_name='quote',
            name='windscreen_customization',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='windscreen_app.windscreencustomization'),
        ),
        migrations.AddField(
            model_name='quote',
            name='windscreen_type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='windscreen_app.windscreentype'),
        ),
        migrations.AlterField(
            model_name='order',
            name='quote',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='order', to='windscreen_app.quote'),
        ),
    ]
