# Generated by Django 5.1.6 on 2025-03-06 10:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('windscreen_app', '0022_quote_vehicle_quote_windscreen_customization_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='quote',
            name='windscreen_customization',
            field=models.ForeignKey(default=52, on_delete=django.db.models.deletion.CASCADE, related_name='qoutes', to='windscreen_app.windscreencustomization'),
        ),
        migrations.AlterField(
            model_name='quote',
            name='windscreen_type',
            field=models.ForeignKey(default=57, on_delete=django.db.models.deletion.CASCADE, related_name='quotes', to='windscreen_app.windscreentype'),
        ),
    ]
