# Generated by Django 5.1.6 on 2025-03-06 11:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('windscreen_app', '0023_alter_quote_windscreen_customization_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='quote',
            name='vehicle',
            field=models.ForeignKey(default=140, on_delete=django.db.models.deletion.CASCADE, related_name='quotes', to='windscreen_app.vehicle'),
        ),
    ]
