# Generated by Django 5.1.6 on 2025-03-08 13:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('windscreen_app', '0025_invoice_statementofaccount'),
    ]

    operations = [
        migrations.AddField(
            model_name='quote',
            name='make',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='quote',
            name='model',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='quote',
            name='registration_number',
            field=models.CharField(blank=True, max_length=15),
        ),
        migrations.AlterField(
            model_name='quote',
            name='vehicle',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='quotes', to='windscreen_app.vehicle'),
        ),
        migrations.AlterField(
            model_name='quote',
            name='windscreen_customization',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='quotes', to='windscreen_app.windscreencustomization'),
        ),
        migrations.AlterField(
            model_name='quote',
            name='windscreen_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='quotes', to='windscreen_app.windscreentype'),
        ),
    ]
